export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILURE = "GET_POST_FAILURE"
export const GET_POST_REQUEST = "GET_POST_REQUEST"

export const POST_POST_SUCCESS = "POST_POST_SUCCESS"
export const POST_POST_FAILURE = "POST_POST_FAILURE"
export const POST_POST_REQUEST = "POST_POST_REQUEST"

export const POST_LIKES_SUCCESS = "POST_LIKES_SUCCESS"
export const POST_LIKES_FAILURE = "POST_LIKES_FAILURE"
export const POST_LIKES_REQUEST = "POST_LIKES_REQUEST"

export const POST_COMMENTS_SUCCESS = "POST_COMMENTS_SUCCESS"
export const POST_COMMENTS_FAILURE = "POST_COMMENTS_FAILURE"
export const POST_COMMENTS_REQUEST = "POST_COMMENTS_REQUEST"